# Generated by Django 4.1.6 on 2023-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
