# Generated by Django 4.1.6 on 2023-05-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_trailer'),
        ('theater', '0002_seat_movie_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.CreateModel(
            name='SeatMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='movies',
            field=models.ManyToManyField(through='theater.SeatMovie', to='home.movie'),
        ),
    ]
