# Generated by Django 4.1.6 on 2023-06-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_trailer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theater', '0003_remove_seat_movie_seatmovie_seat_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
            ],
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seat_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='movies',
        ),
        migrations.AddField(
            model_name='seat',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SeatMovie',
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theater.hall'),
        ),
    ]
