# Generated by Django 4.1.6 on 2023-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_alter_hall_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
