# Generated by Django 4.1.6 on 2023-06-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_remove_seat_hall_seat_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
