# Generated by Django 4.1.6 on 2023-06-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_alter_hall_slug_hallseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
    ]
