# Generated by Django 4.1.6 on 2023-05-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_trailer'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
