# Generated by Django 4.1.6 on 2023-05-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
