# Generated by Django 4.1.6 on 2023-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_alter_seat_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
