# Generated by Django 4.1.6 on 2023-04-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('age_limit', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('start_rental', models.DateField()),
                ('end_rental', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('production', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('starring', models.TextField()),
                ('description', models.TextField()),
                ('released', models.BooleanField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.category')),
            ],
        ),
    ]
