# Generated by Django 4.1.6 on 2023-06-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category / Genre',
                'verbose_name_plural': 'Categories / Genres',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.CharField(max_length=255, null=True)),
                ('age_limit', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('start_rental', models.DateField()),
                ('end_rental', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('production', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('starring', models.TextField()),
                ('description', models.TextField()),
                ('cat', models.ManyToManyField(to='home.category')),
                ('state', models.ManyToManyField(to='home.state')),
            ],
        ),
    ]
