# Generated by Django 4.1.6 on 2023-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category / Genre', 'verbose_name_plural': 'Categories / Genres'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cat',
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Released date'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cat',
            field=models.ManyToManyField(to='home.category'),
        ),
    ]
