# Generated by Django 4.1.6 on 2023-05-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_state_remove_movie_released_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
